baseURL = "https://tonienaszawojna.org"
title = "#ToNieNaszaWojna"
languageCode = "pl"

defaultContentLanguage = 'pl'
defaultContentLanguageInSubdir = true

# preservetaxonomynames = true
tags = ["website", "responsive", "Multilingual"]
theme = ["hugo-travelify-theme"]
timeZone = "Europe/Warsaw"
GoogleAnalytics = "" # Add your own Google analytics code here in the format UA-XXXXXXXX-X
canonifyURLs = true
disableHugoGeneratorInject = true
disableLiveReload = true

paginate = 12

enableEmoji = true
#enableGitInfo = true
enableRobotsTXT = true

# rssURI = "feed/" #deprecated feature

[languages]
  [languages.pl]
    contentDir = 'content/polish'
    languageName = 'Polski'
    title = '#ToNieNaszaWojna'
    weight = 1
    [languages.pl.params]
      author = "Polski Ruch Antywojenny"
      site_description = "Polski Ruch Antywojenny"
      recent_articles = "Ostatnie wiadomości"
      menu_aside = "Kategorie"
      read_more = "Czytaj więcej"
[[languages.pl.menu.main]]
    name  = "O nas"
    url   = "/pl/post/about/"
    weight = 10
[[languages.pl.menu.main]]
    name  = "Deklaracja"
    url   = "/pl/post/statement/"
    weight = 20

[[languages.pl.menu.main]]
    name  = "Nasze inicjatywy"
    url   = "/pl/activities/"
    weight = 30

[[languages.pl.menu.main]]
    name  = "Logotypy do pobrania"
    url   = "/pl/logotypes/"
    weight = 40

[[languages.pl.menu.main]]
    name  = "Grafiki do druku"
    url   = "/pl/graphics/"
    weight = 50

[[languages.pl.menu.main]]
    name  = "Wsparcie"
    url   = "/pl/support/"
    weight = 60
    
[[languages.pl.menu.main]]
    name  = "Kontakt"
    url   = "/pl/contact/"
    weight = 70 

  [languages.zh]
    contentDir = 'content/chinese'
    languageName = '简体中文'
    title = '#这不是我们的战争'
   weight = 2
    [languages.zh.params]
      author = "波兰反战运动"
      site_description = "波兰反战运动"
      recent_articles = "最近的帖子"
      menu_aside = "类别"
      read_more = "阅读更多"
    [languages.zh.menu]
[[languages.zh.menu.main]]
    name  = "关于"
    url   = "/zh/post/about/"
    weight = 10
[[languages.zh.menu.main]]
    name  = "声明"
    url   = "/zh/post/statement/"
    weight = 20

[[languages.zh.menu.main]]
    name  = "活动"
    url   = "/zh/activities/"
    weight = 30

[[languages.zh.menu.main]]
    name  = "可供下载的标识图案"
    url   = "/zh/logotypes/"
    weight = 40

[[languages.zh.menu.main]]
    name  = "打印的图形"
    url   = "/zh/graphics/"
    weight = 50

[[languages.zh.menu.main]]
    name  = "支持"
    url   = "/zh/support/"
    weight = 60
    
[[languages.zh.menu.main]]
    name  = "联系我们"
    url   = "/zh/contact/"
    weight = 70

  [languages.en]
    contentDir = 'content/english'
    languageName = 'English'
    title = '#ThisIsNotOurWar'
   weight = 3
    [languages.en.params]
      author = "Polish Anti-War Movement"
      site_description = "Polish Anti-War Movement"
      recent_articles = "Recent Posts"
      menu_aside = "Categories"
      read_more = "Read More"
    [languages.en.menu]
[[languages.en.menu.main]]
    name  = "About"
    url   = "/en/post/about/"
    weight = 10
[[languages.en.menu.main]]
    name  = "Statement"
    url   = "/en/post/statement/"
    weight = 20

[[languages.en.menu.main]]
    name  = "Activities"
    url   = "/en/activities/"
    weight = 30

[[languages.en.menu.main]]
    name  = "Logotypes to download"
    url   = "/en/logotypes/"
    weight = 40

[[languages.en.menu.main]]
    name  = "Graphics to print"
    url   = "/en/graphics/"
    weight = 50

[[languages.en.menu.main]]
    name  = "Support"
    url   = "/en/support/"
    weight = 60
    
[[languages.en.menu.main]]
    name  = "Contact"
    url   = "/en/contact/"
    weight = 70

  [languages.ru]
    contentDir = 'content/russian'
    languageName = 'Русский'
    title = '#ЭтоНеНашаВойна'
    weight = 4
    [languages.ru.params]
      author = "Антивоенное Движение Польши"
      site_description = "Антивоенное Движение Польши"
      recent_articles = "Последние сообщения"
      menu_aside = "Категории"
      read_more = "Читать далее"
[[languages.ru.menu.main]]
    name  = "О нас"
    url   = "/ru/post/about/"
    weight = 10
[[languages.ru.menu.main]]
    name  = "Заявление"
    url   = "/ru/post/statement/"
    weight = 20

[[languages.ru.menu.main]]
    name  = "Наши инициативы"
    url   = "/ru/activities/"
    weight = 30

[[languages.ru.menu.main]]
    name  = "Логотипы для скачивания"
    url   = "/ru/logotypes/"
    weight = 40

[[languages.ru.menu.main]]
    name  = "Графика для печати"
    url   = "/ru/graphics/"
    weight = 50

[[languages.ru.menu.main]]
    name  = "Поддержка"
    url   = "/ru/support/"
    weight = 60
    
[[languages.ru.menu.main]]
    name  = "Контакт"
    url   = "/ru/contact/"
    weight = 70

  [languages.hu]
    contentDir = 'content/hungarian'
    languageName = 'Magyar'
    title = '#EzNemAMiHáborúnk'
   weight = 5
    [languages.hu.params]
      author = "Lengyel Háborúellenes Mozgalom"
      site_description = "Lengyel Háborúellenes Mozgalom"
      recent_articles = "Legutóbbi bejegyzések"
      menu_aside = "Kategóriák"
      read_more = "Olvass tovább"
    [languages.hu.menu]
[[languages.hu.menu.main]]
    name  = "Rólunk"
    url   = "/hu/post/about/"
    weight = 10
[[languages.hu.menu.main]]
    name  = "Magyarázat"
    url   = "/hu/post/statement/"
    weight = 20

[[languages.hu.menu.main]]
    name  = "Kezdeményezések"
    url   = "/hu/activities/"
    weight = 30

[[languages.hu.menu.main]]
    name  = "Letölthető logotípusok"
    url   = "/hu/logotypes/"
    weight = 40

[[languages.hu.menu.main]]
    name  = "Grafika nyomtatáshoz"
    url   = "/hu/graphics/"
    weight = 50

[[languages.hu.menu.main]]
    name  = "Támogatás"
    url   = "/hu/support/"
    weight = 60
    
[[languages.hu.menu.main]]
    name  = "Kapcsolat"
    url   = "/hu/contact/"
    weight = 70

  [languages.sk]
    contentDir = 'content/slovak'
    languageName = 'Slovenská'
    title = '#TotoNieJeNašaWojna'
   weight = 6
    [languages.sk.params]
      author = "Poľské Protivojnové Hnutie"
      site_description = "Poľské Protivojnové Hnutie"
      recent_articles = "Najnovšie príspevky"
      menu_aside = "Kategórie"
      read_more = "Čítajte viac"
    [languages.sk.menu]
[[languages.sk.menu.main]]
    name  = "O nás"
    url   = "/sk/post/about/"
    weight = 10
[[languages.sk.menu.main]]
    name  = "Vyhlásenie"
    url   = "/sk/post/statement/"
    weight = 20

[[languages.sk.menu.main]]
    name  = "Iniciatívy"
    url   = "/sk/activities/"
    weight = 30

[[languages.sk.menu.main]]
    name  = "Logá na stiahnutie"
    url   = "/sk/logotypes/"
    weight = 40

[[languages.sk.menu.main]]
    name  = "Grafika na tlač"
    url   = "/sk/graphics/"
    weight = 50

[[languages.sk.menu.main]]
    name  = "Podpora"
    url   = "/sk/support/"
    weight = 60
    
[[languages.sk.menu.main]]
    name  = "Kontakt"
    url   = "/sk/contact/"
    weight = 70

  [languages.tr]
    contentDir = 'content/turkish'
    languageName = 'Türkçe'
    title = '#BuBizimSavaşımızDeğil'
   weight = 7
    [languages.tr.params]
      author = "Polonya Savaş Karşıtı Hareketi"
      site_description = "Polonya Savaş Karşıtı Hareketi"
      recent_articles = "Son gönderiler"
      menu_aside = "Kategoriler"
      read_more = "Devamını oku"
    [languages.tr.menu]
[[languages.tr.menu.main]]
    name  = "Hakkımızda"
    url   = "/tr/post/about/"
    weight = 10
[[languages.tr.menu.main]]
    name  = "Açıklama"
    url   = "/tr/post/statement/"
    weight = 20

[[languages.tr.menu.main]]
    name  = "Girişimler"
    url   = "/tr/activities/"
    weight = 30

[[languages.tr.menu.main]]
    name  = "İndirilecek logotipler"
    url   = "/tr/logotypes/"
    weight = 40

[[languages.tr.menu.main]]
    name  = "Yazdırılacak grafikler"
    url   = "/tr/graphics/"
    weight = 50

[[languages.tr.menu.main]]
    name  = "Destek"
    url   = "/tr/support/"
    weight = 60
    
[[languages.tr.menu.main]]
    name  = "İletişim"
    url   = "/tr/contact/"
    weight = 70

  [languages.de]
    contentDir = 'content/german'
    languageName = 'Deutsch'
    title = '#DasIstNichtUnserKrieg'
   weight = 8
    [languages.de.params]
      author = "Polnische Anti-Kriegs-Bewegung"
      site_description = "Polnische Anti-Kriegs-Bewegung"
      recent_articles = "Neueste Beiträge"
      menu_aside = "Kategorien"
      read_more = "Mehr lesen"
    [languages.de.menu]
[[languages.de.menu.main]]
    name  = "Über uns"
    url   = "/de/post/about/"
    weight = 10
[[languages.de.menu.main]]
    name  = "Erklärung"
    url   = "/de/post/statement/"
    weight = 20

[[languages.de.menu.main]]
    name  = "Initiativen"
    url   = "/de/activities/"
    weight = 30

[[languages.de.menu.main]]
    name  = "Logotypen zum Herunterladen"
    url   = "/de/logotypes/"
    weight = 40

[[languages.de.menu.main]]
    name  = "Grafiken zum Drucken"
    url   = "/de/graphics/"
    weight = 50

[[languages.de.menu.main]]
    name  = "Unterstützung"
    url   = "/de/support/"
    weight = 60
    
[[languages.de.menu.main]]
    name  = "Kontakt"
    url   = "/de/contact/"
    weight = 70

[[cascade]]

[cascade._target]
  kind = 'page'
  lang = 'pl'
  environment = 'production'

[params]
    copyright  = "Copyright"
    #avatar = ""
    logo = "logo.png"
    title_in_logo = true # set to true if you want the title along with the logo
    disable_mathjax = true # set to true to disable MathJax
    sitename = "Polski Ruch Antywojenny"
    ogimage = "https://tonienaszawojna.org/Logo_Ruch.png"
    # Format dates with Go's time formatting
    date_format = '2021-11-03T12:34:56+01:00'
    description = "To nie nasza wojna,这不是我们的战争,This is not our war,Это не наша война,Das ist Nicht unser Krieg,Ez nem a mi háborúnk,Toto nie je naša vojna,Bu bizim savaşımız değil"
    twitter_cards = true
    images = ["Logo_Ruch.png"]
    # Add custom assets with their paths relative to the static folder
    custom_css = []
    custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.

#[[menu.main]]
#    name  = "Contact21"
#    url   = "/contact/"
#    parent = "Contact2"
#    weight = 20

#[[menu.main]]
#    name  = "cOntact22"
#    url   = "/contact/"
#    parent = "Contact2"
#    weight = 10

#[[menu.main]]
#    name  = "cOntact3"
#    url   = "/contact/"
#    parent = "contact"
		
[params.share]
    enable = true
    facebook = true
    twitter = true
#    linkedin = true
#    email = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[params.privacy]
enable = true # false implies switching on tracking application, you can individually turn off applications that you don't want. If enable = true, then all tracking apps are switched off
facebook_like = true
DisqusShortname = "example"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
#    rss             = "" # leave this to blank if you do not want RSS feed icon to appear on top
#    github          = "example"
#    flickr          = "example"
#    instagram       = "example"
    youtube         = "@SykulskiLeszek"
#    vimeo           = "example"
#    tumblr          = "example"
#    linkedin        = "example"
#    pinterest       = "example"
    facebook        = "PolskiRuchAntywojenny"
    twitter         = "ruchantywojenny"
#    email           = "joe@example.com"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    tags = false
    tag_cloud = false
    archives = false # This feature is yet to be implemented because of limitations in Hugo's way of working.
#    search = true
#    mailchimp = true
#    mailchimpform = "//balaramadurai.us15.list-manage.com/subscribe/post?u=7f4183fa2fe7abe3dc9f4efad&amp;id=49a3dd3745"
    author = false

[params.slider]
    enable = true
    manual = false # Setting manual to true renders the slide selection to only those where the post has a slider=true option enabled
    num_features = -1 # The slider picks up the banner images from the N most recent posts, where num_features is N.
    
[permalinks]
    #categories = "/categories/:slug/" #can be changed to "/category/:slug/"
    tags = "/tags/:slug/"

[taxonomies]
    #category = "categories"
    tag = "tags"
    series = "series"
    author = "author"

[params.views]
    enable = true  # visitor badge from https://visitor-badge.glitch.me/

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

## DONE - Menu
## DONE - slider 
## DONE - facebook like on homepage
## DONE - category URL to work
## DONE - footer
## DONE - add tags to the footer
## TODO - some posts without banner

